### ISSUE TITLE
Instrument FGS missing from Data Quality Inspection 

### ISSUE THREAD

**Issue by marcio-melendez** [spacetelescope/stginga#188]
There is no FGS instrument in the DQ flag dictionary, thus it doesn't load the appropriate JWST DQ flags when opening an FGS image.

**Comment by pllim** [comment]
Did you try to customize it with `~/.ginga/plugin_DQInspect.cfg` as stated in https://stginga.readthedocs.io/en/latest/stginga/plugins_manual/dqinspect.html ?

Are you reporting that customizing does not work? Or are you requesting that FGS should be recognized by default?

**Comment by pllim** [comment]
As for adding it to software default, it is quite tricky without a backward incompatible code change. This is due to the fact that both HST and JWST have FGS, and the plugin only takes in instrument name without the context of which telescope it belongs to.

Are you okay with a backward incompatible change, which would make the plugin ask for both telescope and instrument names?

p.s. The current design was probably an oversight by Past Self ™️ and for that, I deeply apologize.

**Comment by marcio-melendez** [comment]
@pllim with the customization to the plugin_DQInspect.cfg file it works as expected. I was doing it incorrectly, sorry. 

As for the default, I think it would make sense to have the plugin calling both the telescope and the instrument. This may be useful in the future if more JWST FGS specific functions are requested, which is a strong possibility. What do you think?

**Comment by pllim** [comment]
> What do you think?

I agree. I'll whip up something and ping you for review.
