### ISSUE TITLE
BadPixCorr plugin might be incompatible with Ginga v4

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#227]
`stginga/plugins/BadPixCorr.py` circle drawing acts weird now. To reproduce this problem:

1. Load an image with SCI and DQ arrays and real bad pixels.
2. Start BadPixCorr plugin.
3. Select a bad pixel to fix by clicking on it. By default, it draws a circle and an annulus around it.

Problem: Circle has zero radius. Setting the line below from 0 to 1 has no effect.

https://github.com/spacetelescope/stginga/blob/8d0e3b02e9a0194de57245e8978e7d140b021171/stginga/plugins/BadPixCorr.py#L87

I think `obj.radius` comes back zero even if I try to draw a bigger circle.

https://github.com/spacetelescope/stginga/blob/8d0e3b02e9a0194de57245e8978e7d140b021171/stginga/plugins/BadPixCorr.py#L359

Suspect:

* https://github.com/ejeschke/ginga/pull/973

cc @ejeschke @kulpster85

**Comment by ejeschke** [comment]
@pllim, is this with the current (dev) version of Ginga?

**Comment by pllim** [comment]
Yes, current dev version I pulled from GitHub today.

**Comment by ejeschke** [comment]
How big should the circle normally be relative to the annulus?  In the GUI for `BadPixCorr`, if I type a number into the box labeled "Radius:" (under "Bad Pix Attributes") and press enter, it shows a green circle of that radius (in addition to the magenta annulus).  Is it possible that the field is being initialized to 0 incorrectly?

**Comment by pllim** [comment]
Yes, `obj.radius` returns zero. In your Drawing plugin, it defaults to 1. I don't understand why it does not default to 1 anymore in this plugin. 😿

**Comment by ejeschke** [comment]
I see that when I actually drag out a circle instead of just clicking, I get a circle of the desired radius.  Not sure why the previous version should have defaulted to 1 with just a click, because it is certainly possible to draw a circle with a radius close to zero.

If change L359 from
```python
self.radius = obj.radius
```
to
```python
self.radius = max(obj.radius, 1.0)
obj.radius = self.radius
```
I think the plugin works like you are describing.

**Comment by ejeschke** [comment]
PR in #228

**Comment by ejeschke** [comment]
When I try the `Drawing` plugin, one can easily draw *very* tiny circles.  I think the 1.0 in the 'radius:' box is not meaningful for the drawing operation itself, since the radius is determined by how far you drag the cursor while the button is held.  Instead, it changes to the actual radius if you try to edit the object.

**Comment by pllim** [comment]
Thanks! I'll have a look tomorrow. 🙇‍♀️

**Comment by pllim** [comment]
Works fine. Thanks again!
