### ISSUE TITLE
Class autodoc not showing on RTD

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#82]
For example, this page is empty but it is supposed to show two classes:
http://stginga.readthedocs.org/en/latest/api/local_plugin_mixin.html

I do not have this problem with `make html` locally on my machine. There must be some assumption that RTD makes that I do not know about?

All I am doing is using `automodule`! My local `sphinx-build` version is 1.3.1.

**Comment by pllim** [comment]
@eteq , perhaps you have an idea?

**Comment by eteq** [comment]
@pllim If you take a look at the build logs in RTD (i.e. https://readthedocs.org/projects/stginga/builds/3689655/) you'll see this:
`/home/docs/checkouts/readthedocs.org/user_builds/stginga/checkouts/latest/docs/source/api/local_plugin_mixin.rst:6: WARNING: autodoc: failed to import module u'stginga.plugins.local_plugin_mixin'; the following exception was raised`

Looking at the related traceback, I think the problem is that it can't import that module because it can't import the parts of ginga that require qt to be installed.  My first guess at a solution is to try to force qt to install by adding it to `docs/rtd-pip-requirements`... But of course QT is notoriously finicky to install.  It might be that instead you'll need to fiddle around with imports to keep it from trying to access qt stuff at doc-build time?

**Comment by pllim** [comment]
Thanks, @eteq ! Oh, I didn't know I can expand the text, so I missed the warnings. Ops! You're right, moving the import is probably the right thing to do. Thank you!

**Comment by pllim** [comment]
Attempted fix is cd16e7e3b0d8. Waiting for build.

**Comment by pllim** [comment]
Fixed!
