### ISSUE TITLE
RTD to use system packages

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stginga#91]
As a result of `scipy` dependency added in #90, RTD is now failing (see  https://readthedocs.org/projects/stginga/builds/3729768/ ). I think the solution is same as nmearl/pyfocal#34, that is the owner of our RTD account (@eteq) needs to "go to the Advanced settings section in your project's admin panel and select the checkbox in Use system packages."

**Comment by eteq** [comment]
@pllim - OK, I did as you suggest and RTD has now built successfully https://readthedocs.org/projects/stginga/builds/3730208/

One possible danger of using system packages: if you later on decide you _need_ a different version of one of the scipy packages, you may have to fight with RTD to make sure it uses the one you asked for rather than the one that's on the system.  I haven't had that problem in a while, so maybe they fixed it, but just something to be aware of, @nmearl and @pllim

**Comment by pllim** [comment]
Noted. Thanks, @eteq !
